import type { Metadata } from 'next'
import './globals.css'
import { Manrope } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import AppProvider from '@/context/app.context'
import { ThemeProvider } from '@/components/theme-provider'
import Header from '@/components/header'
import Footer from '@/components/footer'
const manrope = Manrope({ subsets: ['latin'], variable: '--font-manrope' })
export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app'
}

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang='en' suppressHydrationWarning>
         <body className={`${manrope.className} antialiased text-sm font-normal`}>
            <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
               <AppProvider>
                  <Header />
                  <main className='py-5 container'>{children}</main>
                  <Footer />
               </AppProvider>
               <ToastContainer />
            </ThemeProvider>
         </body>
      </html>
   )
}
